# vim:ft=sh noet:
umask 022

# "." コマンドでシェルスクリプトを実行するときは
# 混乱するので PATH を検索させない。
shopt -u sourcepath

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# ^C が残る対策
[ -t 0 ] && stty -ctlecho

# 履歴
HISTSIZE=50000
HISTFILESIZE=50000
shopt -s histappend
shopt -u hostcomplete
shopt -s checkhash

# PROMPT
PS1="[@\h \W]\$ "

# 設定ファイルのinclude
[ -f ~/.bash_local ] && . ~/.bash_local
