---
- name: check wsl
  shell: "[ -e /mnt/c/Windows/System32/wsl.exe ] && echo 'y' || echo 'n'"
  register: setup_wsl

- name: get tz
  shell: timedatectl | grep 'Time zone'
  when:
    - "setup_wsl.stdout == 'n'"
  register: setup_tz

- name: change tz to JST
  when:
    - "setup_wsl.stdout == 'n'"
    - "'stdout' in setup_tz"
    - "'Asia/Tokyo' not in setup_tz.stdout"
  become: yes
  command: timedatectl set-timezone Asia/Tokyo

- name: (RedHat cor) install epel-release
  when: ansible_os_family == "RedHat" and ansible_distribution_version|int < 8
  become: yes
  package:
    name:
      - epel-release
      - epel-next-release
    state: present

- name: (RedHat cor) install the 'Development tools' package group
  when: ansible_os_family == "RedHat"
  become: yes
  package:
    name: "@Development tools"
    state: present

- name: (Debian cor) install build-essential
  when: ansible_os_family == "Debian"
  become: yes
  package:
    name: build-essential
    state: present

- name: install tmux
  become: yes
  package:
    name: tmux
    state: latest

- name: create work dir
  become: yes
  file: path="{{work_dir}}" state=directory

- name: create flag file
  become: yes
  file:
    path: "{{setup.flag_fpaht}}"
    state: touch

# vim:ft=yaml sts=2 sw=2:
