---
- name: (RedHat) install build depends
  when: ansible_os_family == "RedHat"
  become: yes
  package:
    name:
      - dh-autoreconf
      - curl-devel
      - expat-devel
      - gettext-devel
      - openssl-devel
      - perl-devel
      - zlib-devel
      - asciidoc
      - xmlto
      - docbook2X
    state: present

- name: (RedHat) create docbook2x-texi symbolic link
  when: ansible_os_family == "RedHat"
  become: yes
  file:
    src: /usr/bin/db2x_docbook2texi
    dest: /usr/bin/docbook2x-texi
    state: link

- name: (Debian) install build depends
  when: ansible_os_family == "Debian"
  become: yes
  package:
    name:
      - dh-autoreconf
      - libcurl4-gnutls-dev
      - libexpat1-dev
      - gettext
      - libz-dev
      - libssl-dev
      - asciidoc
      - xmlto
      - docbook2x
      - install-info
    state: present

- name: fetch and extrace src archive
  become: yes
  unarchive:
    src: "{{git_src_url}}"
    dest: "{{work_dir}}"
    remote_src: yes

- name: make configure
  become: yes
  command: make configure
  args:
    chdir: "{{git_unarchived}}"

- name: configure
  become: yes
  command: ./configure --prefix="{{git_prefix}}"
  args:
    chdir: "{{git_unarchived}}"

- name: make
  become: yes
  command: make all doc info
  args:
    chdir: "{{git_unarchived}}"

- name: make install
  become: yes
  command: make install install-doc install-html install-info
  args:
    chdir: "{{git_unarchived}}"

# vim:ft=yaml sts=2 sw=2:
