---
- name: cp repo file
  become: yes
  copy: >-
    src=fc22-home-ocaml.repo
    dest=/etc/yum.repos.d/home:ocaml.repo

- name: install opam
  become: yes
  package: name=opam state=latest

- name: install patch
  become: yes
  package: name=patch state=latest

- name: init opam
  command: opam init --comp={{ocaml.version}}

- name: install ocaml
  command: opam switch {{ocaml.version}}

- name: add opam config env
  shell: >-
    sed -i -e
    's/^#eval `opam config env`$/eval `opam config env`/'
    ~/.bash.include

# vim:sts=2 sw=2:
