---
- hosts: all
  gather_facts: True
  vars:
    hostname: "vm"
    email: "quickness.net@gmail.com"
    prefix: "/opt/own"
    work_dir: "/opt/own/work"
    setup:
      flag_fpaht: "/opt/own/work/.setup_flag_file"
    git:
      version: "2.37.1"
    vim:
      version: "8.1.0547"
    python:
      py27_version: "2.7.18"
      py36_version: "3.6.15"
      py37_version: "3.7.12"
      py38_version: "3.8.13"
      py39_version: "3.9.13"
    ocaml:
      version: "4.02.3"
    terraform:
      version: "0.11.7"
  roles:
    - role: 'setup'
      tags: 'always'
    - role: 'git'
      tags: ['never', 'git']
    - role: 'vim'
      tags: ['never', 'vim']
    - role: 'python'
    - role: 'terraform'
      tags: ['never', 'terraform']
    - role: 'ocaml'
      tags: ['never', 'ocaml']

# vim:ft=yaml sts=2 sw=2:
